---
- name: Hello World Sample
  hosts: pa
  
  tasks:
    - name: execute
      panos_op:
         cmd: 'show system info'
         ip_address: '{{ ansible_host }}'
         username: '{{ ansible_ssh_user }}'
         password: '{{ ansible_ssh_pass }}'
      register: show 
    - name: show
      debug:
        var: 'show.stdout'
